version: '3.6'
services:
  app:
    build:
      context: ./app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - 5000-5002:5000
  redis:
    image: redis:5.0.3-alpine
    volumes:
      - redis_data:/data
    container_name: image-app_redis
volumes:
  redis_data:
